# Generated by Django 5.1 on 2025-08-31 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRequestFromClient',
            fields=[
                ('refund_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=100, null=True)),
                ('client_code', models.CharField(max_length=100, null=True)),
                ('client_id', models.CharField(max_length=100, null=True)),
                ('client_txn_id', models.CharField(max_length=100, null=True)),
                ('message', models.TextField(null=True)),
                ('refund_complete_date', models.DateTimeField(null=True)),
                ('refund_init_date', models.DateTimeField(null=True)),
                ('sp_txn_id', models.CharField(max_length=100, null=True)),
                ('login_id', models.IntegerField(null=True)),
                ('refunded_bank_ref_id', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'refund_request_from_client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('txn_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('client_id', models.IntegerField()),
                ('client_name', models.CharField(max_length=200)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('settlement_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(max_length=50)),
                ('refund_status_code', models.CharField(max_length=20, null=True)),
                ('refund_date', models.CharField(max_length=100, null=True)),
                ('refunded_date', models.DateTimeField(null=True)),
                ('refund_message', models.TextField(null=True)),
                ('refund_reason', models.CharField(max_length=500, null=True)),
                ('refunded_amount', models.FloatField(null=True)),
                ('refund_amount', models.FloatField(null=True)),
                ('refund_track_id', models.CharField(max_length=100, null=True)),
                ('refund_initiated_on', models.DateTimeField(null=True)),
                ('refund_process_on', models.DateTimeField(null=True)),
                ('refund_request_from', models.CharField(max_length=100, null=True)),
                ('is_refunded', models.BooleanField(default=False)),
                ('is_settled', models.BooleanField(default=False)),
                ('settlement_date', models.DateTimeField(null=True)),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'transaction_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefundApprovalWorkflow',
            fields=[
                ('workflow_id', models.AutoField(primary_key=True, serialize=False)),
                ('refund_id', models.IntegerField()),
                ('stage', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=20)),
                ('action_by', models.CharField(max_length=100)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(null=True)),
                ('next_stage', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'refund_approval_workflow',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RefundBatch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_reference', models.CharField(max_length=100, unique=True)),
                ('total_refunds', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(default='CREATED', max_length=20)),
                ('file_path', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'refund_batch',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RefundConfiguration',
            fields=[
                ('config_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.IntegerField(unique=True)),
                ('refund_allowed', models.BooleanField(default=True)),
                ('partial_refund_allowed', models.BooleanField(default=False)),
                ('max_refund_days', models.IntegerField(default=180)),
                ('min_refund_amount', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('max_refund_amount', models.DecimalField(decimal_places=2, default=500000, max_digits=12)),
                ('auto_approve_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('requires_l1_approval', models.BooleanField(default=True)),
                ('requires_l2_approval', models.BooleanField(default=True)),
                ('requires_finance_approval', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'refund_configuration',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RefundSettlementAdjustment',
            fields=[
                ('adjustment_id', models.AutoField(primary_key=True, serialize=False)),
                ('refund_id', models.IntegerField()),
                ('txn_id', models.CharField(max_length=100)),
                ('original_settlement_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('adjusted_settlement_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('adjustment_type', models.CharField(max_length=20)),
                ('settlement_date', models.DateField()),
                ('adjusted_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'refund_settlement_adjustments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RefundBatchItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('refund_id', models.IntegerField()),
                ('txn_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('pg_response', models.JSONField(null=True)),
                ('processed_at', models.DateTimeField(null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refunds.refundbatch')),
            ],
            options={
                'db_table': 'refund_batch_items',
                'managed': True,
            },
        ),
    ]
