# Generated by Django 5.1 on 2025-08-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayWebhookLogs',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('gateway_code', models.CharField(max_length=50)),
                ('webhook_type', models.CharField(max_length=50)),
                ('txn_id', models.CharField(max_length=100, null=True)),
                ('pg_txn_id', models.CharField(max_length=100, null=True)),
                ('request_headers', models.JSONField()),
                ('request_body', models.JSONField()),
                ('response_status', models.IntegerField()),
                ('response_body', models.JSONField(null=True)),
                ('signature_valid', models.BooleanField()),
                ('processed', models.BooleanField()),
                ('processing_time_ms', models.IntegerField(null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'gateway_webhook_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebhookConfig',
            fields=[
                ('config_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=50)),
                ('endpoint_url', models.URLField(max_length=500)),
                ('secret_key', models.CharField(max_length=255)),
                ('events_subscribed', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('max_retry_attempts', models.IntegerField(default=3)),
                ('retry_delay_minutes', models.IntegerField(default=5)),
                ('timeout_seconds', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'webhook_config',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WebhookEventQueue',
            fields=[
                ('queue_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=100)),
                ('event_data', models.JSONField()),
                ('status', models.CharField(default='QUEUED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(null=True)),
                ('error_message', models.TextField(null=True)),
            ],
            options={
                'db_table': 'webhook_event_queue',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WebhookLogs',
            fields=[
                ('webhook_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=50)),
                ('config_id', models.IntegerField()),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('endpoint_url', models.URLField(max_length=500)),
                ('delivery_status', models.CharField(default='PENDING', max_length=20)),
                ('http_status_code', models.IntegerField(null=True)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(null=True)),
                ('signature_sent', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'webhook_logs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WebhookTemplate',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100, unique=True)),
                ('payload_template', models.JSONField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'webhook_templates',
                'managed': True,
            },
        ),
    ]
