# Generated by Django 5.1 on 2025-08-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('txn_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pg_txn_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=50)),
                ('pg_name', models.CharField(blank=True, max_length=50, null=True)),
                ('pg_response_code', models.CharField(blank=True, max_length=50, null=True)),
                ('resp_msg', models.TextField(blank=True, null=True)),
                ('refund_status_code', models.CharField(blank=True, max_length=50, null=True)),
                ('refunded_date', models.DateTimeField(blank=True, null=True)),
                ('refunded_amount', models.FloatField(blank=True, null=True)),
                ('is_refunded', models.BooleanField(default=False)),
                ('refund_message', models.TextField(blank=True, null=True)),
                ('is_settled', models.BooleanField(default=False)),
                ('settlement_date', models.DateTimeField(blank=True, null=True)),
                ('settlement_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transaction_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GatewayConfiguration',
            fields=[
                ('gateway_id', models.AutoField(primary_key=True, serialize=False)),
                ('gateway_name', models.CharField(max_length=100, unique=True)),
                ('gateway_code', models.CharField(max_length=50, unique=True)),
                ('api_endpoint', models.URLField()),
                ('status_check_endpoint', models.URLField()),
                ('refund_endpoint', models.URLField(blank=True, null=True)),
                ('api_key', models.CharField(max_length=255)),
                ('api_secret', models.CharField(max_length=255)),
                ('webhook_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('timeout_seconds', models.IntegerField(default=30)),
                ('max_retry_attempts', models.IntegerField(default=3)),
                ('retry_delay_seconds', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('supports_webhook', models.BooleanField(default=True)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gateway_configurations',
            },
        ),
        migrations.CreateModel(
            name='GatewaySyncLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('sync_queue_id', models.IntegerField()),
                ('operation', models.CharField(max_length=50)),
                ('request_url', models.URLField()),
                ('request_method', models.CharField(max_length=10)),
                ('request_headers', models.JSONField()),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_headers', models.JSONField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gateway_sync_logs',
                'indexes': [models.Index(fields=['sync_queue_id'], name='gateway_syn_sync_qu_7ae10f_idx'), models.Index(fields=['created_at'], name='gateway_syn_created_81c44c_idx')],
            },
        ),
        migrations.CreateModel(
            name='GatewaySyncQueue',
            fields=[
                ('sync_id', models.AutoField(primary_key=True, serialize=False)),
                ('txn_id', models.CharField(max_length=100)),
                ('pg_txn_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sync_type', models.CharField(max_length=50)),
                ('priority', models.IntegerField(default=1)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gateway_sync_queue',
                'indexes': [models.Index(fields=['status', 'priority', 'next_retry_at'], name='gateway_syn_status_2dd1e1_idx'), models.Index(fields=['txn_id'], name='gateway_syn_txn_id_835667_idx'), models.Index(fields=['created_at'], name='gateway_syn_created_7a0e45_idx')],
            },
        ),
        migrations.CreateModel(
            name='GatewayWebhookLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('gateway_code', models.CharField(max_length=50)),
                ('webhook_type', models.CharField(max_length=50)),
                ('txn_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pg_txn_id', models.CharField(blank=True, max_length=100, null=True)),
                ('request_headers', models.JSONField()),
                ('request_body', models.JSONField()),
                ('response_status', models.IntegerField()),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('signature_valid', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gateway_webhook_logs',
                'indexes': [models.Index(fields=['txn_id'], name='gateway_web_txn_id_023dca_idx'), models.Index(fields=['created_at'], name='gateway_web_created_9d459e_idx'), models.Index(fields=['gateway_code'], name='gateway_web_gateway_069458_idx')],
            },
        ),
    ]
