# Generated by Django 5.1 on 2025-08-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUserActivityLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('activity', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(null=True)),
                ('entity_type', models.CharField(max_length=50, null=True)),
                ('entity_id', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'admin_user_activity_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientDataTable',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_code', models.CharField(max_length=50)),
                ('client_name', models.CharField(max_length=200)),
                ('kyc_status', models.CharField(default='PENDING', max_length=20)),
                ('kyc_verified_date', models.DateTimeField(null=True)),
                ('risk_category', models.CharField(default='LOW', max_length=20)),
                ('pan_number', models.CharField(max_length=10)),
                ('gst_number', models.CharField(max_length=15, null=True)),
                ('agreement_status', models.CharField(default='PENDING', max_length=20)),
                ('agreement_date', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'client_data_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('txn_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('client_id', models.IntegerField()),
                ('client_name', models.CharField(max_length=200)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_mode', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('kyc_status', models.CharField(max_length=20, null=True)),
                ('risk_score', models.IntegerField(null=True)),
                ('payee_email', models.EmailField(max_length=200, null=True)),
                ('payee_mob', models.CharField(max_length=15, null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'transaction_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComplianceAlert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=20)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('reviewed_by', models.CharField(max_length=100, null=True)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('action_taken', models.TextField(null=True)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('metadata', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'compliance_alerts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RBIReportLog',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=50)),
                ('report_period_start', models.DateField()),
                ('report_period_end', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=20)),
                ('submission_ref', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'rbi_report_log',
                'managed': True,
            },
        ),
    ]
