# Generated by Django 5.1 on 2025-08-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDataTable',
            fields=[
                ('client_id', models.IntegerField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, default=False, null=True)),
                ('auth_flag', models.BooleanField(blank=True, default=True, null=True)),
                ('auth_key', models.TextField()),
                ('auth_type', models.TextField(blank=True, null=True)),
                ('client_code', models.TextField(blank=True, null=True, unique=True)),
                ('client_contact', models.TextField()),
                ('client_email', models.TextField(blank=True, null=True)),
                ('auth_iv', models.TextField()),
                ('client_name', models.TextField()),
                ('client_pass', models.TextField()),
                ('client_type', models.TextField(blank=True, null=True)),
                ('client_user_name', models.TextField()),
                ('created_by', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('enquiry_flag', models.BooleanField(blank=True, default=False, null=True)),
                ('failed_ru_url', models.TextField()),
                ('is_application', models.BooleanField(blank=True, default=False, null=True)),
                ('push_api_flag', models.BooleanField(blank=True, default=False, null=True)),
                ('push_api_url', models.TextField()),
                ('refund_applicable', models.BooleanField(blank=True, default=False, null=True)),
                ('success_ru_url', models.TextField()),
                ('ui_by_pass', models.BooleanField(blank=True, default=False, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.TextField(blank=True, null=True)),
                ('partner_bank_id', models.IntegerField(blank=True, null=True)),
                ('client_logo_path', models.TextField()),
                ('client_address', models.TextField(blank=True, null=True)),
                ('applicable_for_challan', models.CharField(blank=True, max_length=45, null=True)),
                ('application_appid', models.IntegerField(blank=True, db_column='application_appId', null=True)),
                ('is_refund_applicable', models.TextField(blank=True, null=True)),
                ('loginbean_loginid', models.IntegerField(blank=True, db_column='loginBean_loginId', null=True)),
                ('redirect_to_new_layout', models.TextField(blank=True, null=True)),
                ('duplicate_restriction', models.BooleanField(blank=True, default=False, null=True)),
                ('donation_flag', models.BooleanField(blank=True, default=False, null=True)),
                ('round_off', models.BooleanField(blank=True, default=True, null=True)),
                ('refund_type', models.TextField(blank=True, null=True)),
                ('risk_category', models.IntegerField(blank=True, null=True)),
                ('ispaybylink', models.SmallIntegerField(blank=True, db_column='isPaybyLink', null=True)),
                ('ispaybyform', models.SmallIntegerField(blank=True, db_column='isPaybyForm', null=True)),
                ('mesaage_bypass_flag', models.BooleanField(blank=True, default=False, null=True)),
                ('van_flag', models.BooleanField(blank=True, default=False, null=True)),
                ('tpv_flag', models.BooleanField(blank=True, default=False, null=True)),
                ('abort_job_flag', models.BooleanField(blank=True, default=False, null=True)),
                ('gift_card_flag', models.BooleanField(blank=True, default=False, null=True)),
                ('is_client_logo_flag', models.SmallIntegerField(blank=True, null=True)),
                ('is_commercial_flag', models.SmallIntegerField(blank=True, null=True)),
                ('is_partnerbank_logo_flag', models.SmallIntegerField(blank=True, null=True)),
                ('is_whitelisted', models.BooleanField(blank=True, default=False, null=True)),
                ('api_version', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'client_data_table',
                'ordering': ['-creation_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientFeeBearer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('client_id', models.IntegerField(blank=True, null=True)),
                ('paymode', models.CharField(blank=True, max_length=20, null=True)),
                ('bearer', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Client Fee Bearer',
                'verbose_name_plural': 'Client Fee Bearers',
                'db_table': 'client_fee_bearer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientPaymentMode',
            fields=[
                ('epid', models.IntegerField(primary_key=True, serialize=False)),
                ('client_id', models.IntegerField(blank=True, null=True)),
                ('payment_mode', models.TextField(blank=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('enable', models.BooleanField(blank=True, null=True)),
                ('ep_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Client Payment Mode',
                'verbose_name_plural': 'Client Payment Modes',
                'db_table': 'client_payment_mode',
                'managed': False,
            },
        ),
    ]
