# Generated by Django 5.1 on 2025-09-01 04:46

import clients.document_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.IntegerField(db_index=True)),
                ('document_type', models.CharField(choices=[('PAN', 'PAN Card'), ('AADHAAR', 'Aadhaar Card'), ('GST', 'GST Certificate'), ('BANK_STATEMENT', 'Bank Statement'), ('INCORPORATION', 'Certificate of Incorporation'), ('PARTNERSHIP_DEED', 'Partnership Deed'), ('TRADE_LICENSE', 'Trade License'), ('OTHER', 'Other Document')], max_length=20)),
                ('document_name', models.CharField(max_length=255)),
                ('document_file', models.FileField(max_length=500, upload_to=clients.document_models.client_document_path)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('verified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Client Document',
                'verbose_name_plural': 'Client Documents',
                'db_table': 'client_documents',
                'ordering': ['-upload_date'],
                'managed': True,
                'indexes': [models.Index(fields=['client_id', 'document_type'], name='client_docu_client__d24a14_idx'), models.Index(fields=['status'], name='client_docu_status_2263e9_idx')],
            },
        ),
    ]
