# Generated by Django 5.1 on 2025-09-01 10:29

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('method_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method_code', models.CharField(max_length=50, unique=True)),
                ('method_name', models.CharField(max_length=100)),
                ('method_type', models.CharField(choices=[('CARD', 'Card Payment'), ('NETBANKING', 'Net Banking'), ('UPI', 'UPI'), ('WALLET', 'Digital Wallet'), ('EMI', 'EMI'), ('BNPL', 'Buy Now Pay Later')], max_length=50)),
                ('provider_name', models.CharField(max_length=100)),
                ('provider_code', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_otp', models.BooleanField(default=False)),
                ('requires_3ds', models.BooleanField(default=False)),
                ('min_amount', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, default=100000.0, max_digits=10)),
                ('processing_time', models.IntegerField(default=300)),
                ('success_rate', models.DecimalField(decimal_places=2, default=95.0, max_digits=5)),
                ('icon_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('terms_conditions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_methods',
                'ordering': ['method_type', 'method_name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentConfiguration',
            fields=[
                ('config_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_methods', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('card_enabled', models.BooleanField(default=True)),
                ('card_min_amount', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('card_max_amount', models.DecimalField(decimal_places=2, default=100000.0, max_digits=10)),
                ('card_processing_fee', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('netbanking_enabled', models.BooleanField(default=True)),
                ('netbanking_banks', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('netbanking_processing_fee', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('upi_enabled', models.BooleanField(default=True)),
                ('upi_vpa', models.CharField(blank=True, max_length=255)),
                ('upi_processing_fee', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('wallet_enabled', models.BooleanField(default=False)),
                ('wallet_providers', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('wallet_processing_fee', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('gateway_merchant_id', models.CharField(blank=True, max_length=255)),
                ('gateway_api_key', models.CharField(blank=True, max_length=500)),
                ('gateway_secret_key', models.CharField(blank=True, max_length=500)),
                ('gateway_webhook_secret', models.CharField(blank=True, max_length=500)),
                ('daily_transaction_limit', models.DecimalField(decimal_places=2, default=10000000.0, max_digits=12)),
                ('monthly_transaction_limit', models.DecimalField(decimal_places=2, default=300000000.0, max_digits=12)),
                ('max_transaction_amount', models.DecimalField(decimal_places=2, default=500000.0, max_digits=10)),
                ('min_transaction_amount', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('settlement_cycle', models.CharField(choices=[('T+0', 'Same Day'), ('T+1', 'Next Day'), ('T+2', 'Two Days'), ('T+3', 'Three Days'), ('WEEKLY', 'Weekly')], default='T+1', max_length=20)),
                ('settlement_account_number', models.CharField(blank=True, max_length=50)),
                ('settlement_ifsc_code', models.CharField(blank=True, max_length=15)),
                ('settlement_account_name', models.CharField(blank=True, max_length=255)),
                ('fraud_check_enabled', models.BooleanField(default=True)),
                ('risk_score_threshold', models.IntegerField(default=70)),
                ('auto_refund_enabled', models.BooleanField(default=False)),
                ('duplicate_check_window', models.IntegerField(default=300)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('sync_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_configs', to='clients.clientdatatable')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_configs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_payment_configs', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_payment_configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentConfigurationHistory',
            fields=[
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('ENABLE', 'Enabled'), ('DISABLE', 'Disabled'), ('VERIFY', 'Verified'), ('SYNC', 'Synced')], max_length=20)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('change_reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_config_changes', to=settings.AUTH_USER_MODEL)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_history', to='clients.paymentconfiguration')),
            ],
            options={
                'db_table': 'payment_configuration_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientPaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('custom_fee_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('custom_min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('custom_max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('display_priority', models.IntegerField(default=100)),
                ('custom_display_name', models.CharField(blank=True, max_length=100)),
                ('custom_description', models.TextField(blank=True)),
                ('total_transactions', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('success_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_payment_methods', to='clients.clientdatatable')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.paymentconfiguration')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.paymentmethod')),
            ],
            options={
                'db_table': 'client_payment_methods',
                'ordering': ['display_priority', 'payment_method__method_name'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentconfiguration',
            index=models.Index(fields=['client', 'is_active'], name='client_paym_client__f518f1_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentconfiguration',
            index=models.Index(fields=['sync_status'], name='client_paym_sync_st_ed0c25_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clientpaymentmethod',
            unique_together={('client', 'payment_method')},
        ),
    ]
