# Generated by Django 5.1 on 2025-08-31 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('txn_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('client_id', models.IntegerField()),
                ('client_name', models.CharField(max_length=200)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bank_txn_id', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField()),
                ('reconciliation_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'transaction_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionReconTable',
            fields=[
                ('recon_id', models.AutoField(primary_key=True, serialize=False)),
                ('txn_id', models.CharField(max_length=100)),
                ('client_id', models.IntegerField()),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bank_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('recon_status', models.CharField(max_length=20)),
                ('recon_date', models.DateTimeField(null=True)),
                ('bank_reference', models.CharField(max_length=100, null=True)),
                ('bank_date', models.DateField(null=True)),
                ('remarks', models.TextField(null=True)),
                ('matched_by', models.CharField(max_length=20, null=True)),
                ('matched_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transaction_recon_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BankStatementUpload',
            fields=[
                ('upload_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('bank_name', models.CharField(max_length=100)),
                ('statement_date', models.DateField()),
                ('uploaded_by', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_records', models.IntegerField(default=0)),
                ('matched_records', models.IntegerField(default=0)),
                ('mismatched_records', models.IntegerField(default=0)),
                ('status', models.CharField(default='UPLOADED', max_length=20)),
            ],
            options={
                'db_table': 'bank_statement_uploads',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRule',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(max_length=50)),
                ('match_field', models.CharField(max_length=50)),
                ('tolerance_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('tolerance_days', models.IntegerField(null=True)),
                ('pattern', models.CharField(max_length=255, null=True)),
                ('priority', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reconciliation_rules',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BankStatementEntry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateField()),
                ('value_date', models.DateField()),
                ('description', models.TextField()),
                ('reference_number', models.CharField(max_length=100)),
                ('debit_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('transaction_type', models.CharField(max_length=50)),
                ('matched_txn_id', models.CharField(max_length=100, null=True)),
                ('match_status', models.CharField(default='UNMATCHED', max_length=20)),
                ('match_confidence', models.IntegerField(null=True)),
                ('upload_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reconciliation.bankstatementupload')),
            ],
            options={
                'db_table': 'bank_statement_entries',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReconciliationMismatch',
            fields=[
                ('mismatch_id', models.AutoField(primary_key=True, serialize=False)),
                ('txn_id', models.CharField(max_length=100, null=True)),
                ('mismatch_type', models.CharField(max_length=50)),
                ('system_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('bank_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('system_date', models.DateField(null=True)),
                ('bank_date', models.DateField(null=True)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('resolution', models.TextField(null=True)),
                ('resolved_by', models.CharField(max_length=100, null=True)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_entry_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reconciliation.bankstatemententry')),
            ],
            options={
                'db_table': 'reconciliation_mismatches',
                'managed': True,
            },
        ),
    ]
