# Generated by Django 5.1 on 2025-08-31 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionrecontable',
            options={'managed': True},
        ),
    ]
