# Generated by Django 5.1 on 2025-08-30 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFAConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('require_mfa_for_login', models.BooleanField(default=True)),
                ('require_mfa_for_transactions', models.BooleanField(default=True)),
                ('require_mfa_for_settlements', models.BooleanField(default=True)),
                ('require_mfa_for_configuration', models.BooleanField(default=True)),
                ('max_attempts', models.IntegerField(default=3)),
                ('lockout_duration', models.IntegerField(default=300)),
                ('trusted_device_duration', models.IntegerField(default=30)),
                ('backup_codes_count', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mfa_configurations',
            },
        ),
        migrations.CreateModel(
            name='BackupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mfa_backup_codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_used'], name='mfa_backup__user_id_f9d223_idx'), models.Index(fields=['code'], name='mfa_backup__code_903640_idx')],
            },
        ),
        migrations.CreateModel(
            name='MFAChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_type', models.CharField(max_length=50)),
                ('challenge_code', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('is_successful', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mfa_challenges',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='mfa_challen_user_id_d692d2_idx'), models.Index(fields=['challenge_code'], name='mfa_challen_challen_ced903_idx')],
            },
        ),
        migrations.CreateModel(
            name='MFADevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('device_type', models.CharField(default='totp', max_length=50)),
                ('secret_key', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mfa_devices',
                'ordering': ['-is_primary', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='mfa_devices_user_id_aaf6f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('device_name', models.CharField(max_length=100)),
                ('device_type', models.CharField(max_length=50)),
                ('browser', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('trust_token', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mfa_trusted_devices',
                'ordering': ['-last_used_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='mfa_trusted_user_id_1df35f_idx'), models.Index(fields=['device_id'], name='mfa_trusted_device__add53d_idx'), models.Index(fields=['trust_token'], name='mfa_trusted_trust_t_95313d_idx')],
            },
        ),
    ]
