# Generated by Django 5.1 on 2025-09-01 05:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementConfiguration',
            fields=[
                ('config_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_code', models.CharField(max_length=100, unique=True)),
                ('settlement_cycle', models.CharField(default='T+1', max_length=50)),
                ('min_settlement_amount', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('processing_fee_percentage', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('auto_settle', models.BooleanField(default=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('account_holder_name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'settlement_configurations',
                'ordering': ['client_code'],
            },
        ),
        migrations.CreateModel(
            name='SettlementBatch',
            fields=[
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_date', models.DateField(default=django.utils.timezone.now)),
                ('total_transactions', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_settlement_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'settlement_batches',
                'ordering': ['-batch_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SettlementDetail',
            fields=[
                ('settlement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('txn_id', models.CharField(max_length=255)),
                ('client_code', models.CharField(max_length=100)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('settlement_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('settlement_date', models.DateTimeField(blank=True, null=True)),
                ('settlement_status', models.CharField(default='PENDING', max_length=50)),
                ('bank_reference', models.CharField(blank=True, max_length=150)),
                ('utr_number', models.CharField(blank=True, max_length=150)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='settlements.settlementbatch')),
            ],
            options={
                'db_table': 'settlement_details',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SettlementReconciliation',
            fields=[
                ('reconciliation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_statement_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('system_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('difference_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reconciliation_status', models.CharField(max_length=50)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='settlements.settlementbatch')),
                ('reconciled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'settlement_reconciliations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SettlementReport',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=50)),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='settlements.settlementbatch')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'settlement_reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='settlementbatch',
            index=models.Index(fields=['-batch_date'], name='settlement__batch_d_f5a921_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementbatch',
            index=models.Index(fields=['status'], name='settlement__status_0368e1_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementdetail',
            index=models.Index(fields=['client_code'], name='settlement__client__3056e1_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementdetail',
            index=models.Index(fields=['settlement_status'], name='settlement__settlem_821293_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementdetail',
            index=models.Index(fields=['txn_id'], name='settlement__txn_id_08da1c_idx'),
        ),
    ]
