# Generated by Django 5.1 on 2025-08-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientZoneCodeMapper',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('client_code', models.CharField(blank=True, max_length=10, null=True)),
                ('zone_code', models.CharField(blank=True, max_length=10, null=True)),
                ('original_zone_code', models.CharField(blank=True, max_length=20, null=True)),
                ('userloginid', models.CharField(blank=True, db_column='userLoginId', max_length=100, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('old_userlogin', models.CharField(blank=True, db_column='old_userLogin', max_length=75, null=True)),
                ('zone_head_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'client_zone_code_mapper',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserZoneMapper',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_email', models.CharField(blank=True, max_length=150, null=True)),
                ('zone_code', models.CharField(blank=True, max_length=10, null=True)),
                ('emp_code', models.CharField(blank=True, max_length=20, null=True)),
                ('mgr_code', models.CharField(blank=True, max_length=20, null=True)),
                ('role_id', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'user_zone_mapper',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZoneConfig',
            fields=[
                ('zone_id', models.AutoField(primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=100)),
                ('zone_code', models.CharField(max_length=20, unique=True)),
                ('zone_type', models.CharField(choices=[('GEOGRAPHIC', 'Geographic'), ('BUSINESS_UNIT', 'Business Unit'), ('FUNCTIONAL', 'Functional'), ('REGULATORY', 'Regulatory'), ('TEMPORAL', 'Temporal')], max_length=20)),
                ('parent_zone_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('geographic_bounds', models.JSONField(blank=True, null=True)),
                ('supported_states', models.JSONField(default=list)),
                ('supported_cities', models.JSONField(default=list)),
                ('business_rules', models.JSONField(default=dict)),
                ('transaction_limits', models.JSONField(default=dict)),
                ('allowed_payment_methods', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('auto_assign_new_clients', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'zone_config',
            },
        ),
        migrations.CreateModel(
            name='ClientZoneMapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=50)),
                ('zone_id', models.IntegerField()),
                ('is_primary', models.BooleanField(default=False)),
                ('auto_assigned', models.BooleanField(default=False)),
                ('assignment_reason', models.CharField(max_length=200, null=True)),
                ('effective_from', models.DateTimeField()),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('transaction_routing_priority', models.IntegerField(default=1)),
                ('settlement_preferences', models.JSONField(default=dict)),
                ('fee_configuration', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'client_zone_mapping',
                'unique_together': {('client_id', 'zone_id')},
            },
        ),
        migrations.CreateModel(
            name='UserZoneAccess',
            fields=[
                ('access_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('zone_id', models.IntegerField()),
                ('access_level', models.CharField(choices=[('VIEW', 'View Only'), ('EDIT', 'Edit'), ('ADMIN', 'Administrator'), ('SUPER_ADMIN', 'Super Administrator')], max_length=20)),
                ('granted_by', models.CharField(max_length=100)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('time_restrictions', models.JSONField(default=dict)),
                ('ip_restrictions', models.JSONField(default=list)),
                ('location_restrictions', models.JSONField(default=dict)),
                ('last_accessed', models.DateTimeField(null=True)),
                ('access_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_zone_access',
                'unique_together': {('user_id', 'zone_id')},
            },
        ),
        migrations.CreateModel(
            name='ZoneBasedRestrictions',
            fields=[
                ('restriction_id', models.AutoField(primary_key=True, serialize=False)),
                ('zone_id', models.IntegerField()),
                ('resource_type', models.CharField(choices=[('TRANSACTION', 'Transactions'), ('SETTLEMENT', 'Settlements'), ('REFUND', 'Refunds'), ('REPORT', 'Reports'), ('CLIENT', 'Client Management'), ('USER', 'User Management')], max_length=20)),
                ('allowed_actions', models.JSONField(default=list)),
                ('denied_actions', models.JSONField(default=list)),
                ('amount_limits', models.JSONField(default=dict)),
                ('time_restrictions', models.JSONField(default=dict)),
                ('approval_requirements', models.JSONField(default=dict)),
                ('additional_conditions', models.JSONField(default=dict)),
                ('error_message', models.CharField(max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'zone_based_restrictions',
                'unique_together': {('zone_id', 'resource_type')},
            },
        ),
    ]
